### ISSUE TITLE
Poprawienie błędu

### ISSUE THREAD

**Issue by Zogfryt** [AGH-Narzedzia-Informatyczne/Przelicznik_Wartosci_-Logicznych#19]
a ^ a

**Comment by Zogfryt** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [poprawienie błędu tych samych zmiennych](https://trello.com/c/Dq0dtrHN/16-poprawienie-b%C5%82%C4%99du-tych-samych-zmiennych)

**Comment by AntoniLason** [comment]
Zrobione
